on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
      - name: Send files to server
        id: hello
        uses: sandra2597/sftp-action@v1.26
        with:
          ftp_domain: 'testserversandra.nl'
          ftp_host: 'ssh.strato.com'
          source: 'services'
          target: 'dev'
        env:
          LFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
