on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: sandra2597/sftp-action@v1.8
        with:
          ftp-domain: 'testserversandra.nl'
          ftp-host: 'ssh.strato.com'
        env:
          LFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
